general:
  identity: Admin
  mspid: RZDMSP
  channel: wheelsets
  connectionProfile: /home/vadim/wheelsets-fabric/wheelsets-core/app/blockchain/fabric/config-dev-2orgs.yaml
  configtxpath: $HOME/git/fabchanger/config
  OrgToJoinMSP: VRK2 #OrdererOrg
  myorg: RZD