general:
  identity: Admin
  mspid: Org1MSP
  channel: mychannel
  connectionProfile: /home/vadim/git/fabchanger/config/connection.yaml
  configtxpath: $HOME/git/fabchanger/config
  myorg: Org1
  clientcert: /home/vadim/git/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
  cryptopath: /home/vadim/git/fabric-samples/first-network/crypto-config

connect:
  OrgToJoinMSP: Org8MSP #OrdererOrg
  Org: org8
  Orderer: orderer7
  domain: example.com

broadcast:
  address: localhost:7050
  domain: orderer.example.com
  TLS: true
  RequireClientCert: false
  clientKey:
  clientCert: