general:
  identity: Admin
  mspid: Org2MSP
  channel: mychannel
  connectionProfile: /home/vadim/git/fabchanger/config/connection2.yaml
  configtxpath: $HOME/git/fabchanger/config
  myorg: Org2
  clientcert: /home/vadim/git/fabchanger/config/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

connect:
  OrgToJoinMSP: Org6MSP #OrdererOrg
  Org: org6
  Orderer: orderer7
  domain: example.com